/*
 * Copyright (C) 2017 The Android Open Source Project
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */

package com.android.example.github.vo;

import android.arch.persistence.room.Entity;
import android.arch.persistence.room.Ignore;
import android.arch.persistence.room.Index;
import android.arch.persistence.room.TypeConverters;

import com.amazonaws.mobileconnectors.dynamodbv2.dynamodbmapper.DynamoDBAttribute;
import com.amazonaws.mobileconnectors.dynamodbv2.dynamodbmapper.DynamoDBAutoGeneratedKey;
import com.amazonaws.mobileconnectors.dynamodbv2.dynamodbmapper.DynamoDBHashKey;
import com.amazonaws.mobileconnectors.dynamodbv2.dynamodbmapper.DynamoDBTable;
import com.android.example.github.db.GithubTypeConverters;
import com.android.example.github.walkingTale.Chapter;
import com.android.example.github.walkingTale.ExampleRepo;
import com.google.gson.Gson;
import com.google.gson.annotations.SerializedName;

import java.util.List;

/**
 * Using name/owner_login as primary key instead of id since name/owner_login is always available
 * vs id is not.
 */
@Entity(indices = {@Index("id")},
        primaryKeys = {"name"})
@TypeConverters(GithubTypeConverters.class)
@DynamoDBTable(tableName = "Repo")
public class Repo {
    public static final int UNKNOWN_ID = -1;
    @DynamoDBHashKey(attributeName = "id")
//    @DynamoDBAutoGeneratedKey todo, make id a string so it can be auto generated by ddb
    public int id;
    @SerializedName("name")
    @DynamoDBAttribute(attributeName = "name")
    public String name;
    @SerializedName("description")
    @DynamoDBAttribute(attributeName = "description")
    public String description;
    @SerializedName("chapters")
    @DynamoDBAttribute(attributeName = "chapters")
    public List<Chapter> chapters;
    @SerializedName("genre")
    @DynamoDBAttribute(attributeName = "genre")
    public String genre;
    @SerializedName("tags")
    @DynamoDBAttribute(attributeName = "tags")
    public String tags;
    @SerializedName("duration")
    @DynamoDBAttribute(attributeName = "duration")
    public String duration;
    @SerializedName("rating")
    @DynamoDBAttribute(attributeName = "rating")
    public Double rating;
    @SerializedName("latitude")
    @DynamoDBAttribute(attributeName = "latitude")
    public Double latitude;
    @SerializedName("longitude")
    @DynamoDBAttribute(attributeName = "longitude")
    public Double longitude;
    @SerializedName("story_image")
    @DynamoDBAttribute(attributeName = "story_image")
    public String story_image;

    public Repo(int id, String name, String description, List<Chapter> chapters, String genre, String tags, String duration, Double rating, Double latitude, Double longitude, String story_image) {
        this.id = id;
        this.name = name;
        this.description = description;
        this.chapters = chapters;
        this.genre = genre;
        this.tags = tags;
        this.duration = duration;
        this.rating = rating;
        this.latitude = latitude;
        this.longitude = longitude;
        this.story_image = story_image;
    }

    @Ignore
    public Repo() {
        Repo exampleRepo = ExampleRepo.Companion.getRepo();
        this.id = exampleRepo.id;
        this.name = exampleRepo.name;
        this.description = exampleRepo.description;
        this.chapters = exampleRepo.chapters;
        this.genre = exampleRepo.genre;
        this.tags = exampleRepo.tags;
        this.duration = exampleRepo.duration;
        this.rating = exampleRepo.rating;
        this.latitude = exampleRepo.latitude;
        this.longitude = exampleRepo.longitude;
        this.story_image = exampleRepo.story_image;
    }

    /**
     * @param json A repo in json form
     * @return A repo
     */
    public static Repo fromString(String json) {
        Gson gson = new Gson();
        return gson.fromJson(json, Repo.class);
    }

    public int getId() {
        return id;
    }

    public void setId(int id) {
        this.id = id;
    }

    /**
     * @return The json representation of this repo
     */
    public String toString() {
        Gson gson = new Gson();
        return gson.toJson(this);
    }

    public void setName(String name) {
        this.name = name;
    }

    public void setDescription(String description) {
        this.description = description;
    }

    public void setChapters(List<Chapter> chapters) {
        this.chapters = chapters;
    }

    public void setGenre(String genre) {
        this.genre = genre;
    }

    public void setTags(String tags) {
        this.tags = tags;
    }

    public void setDuration(String duration) {
        this.duration = duration;
    }

    public void setRating(Double rating) {
        this.rating = rating;
    }

    public void setLatitude(Double latitude) {
        this.latitude = latitude;
    }

    public void setLongitude(Double longitude) {
        this.longitude = longitude;
    }

    public void setStory_image(String story_image) {
        this.story_image = story_image;
    }
}
